### ISSUE TITLE
Error occurred when creating the faers object

### ISSUE THREAD

**Issue by powerhorse1986** [Yunuuuu/faers#7]
Hi,

I am trying to learn how to use the package. And I followed the instructions on this github. However, I encountered an error when ran my own code shown as following:

`data1 <- faers(2005, "q4",
               dir = system.file("extdata", package = "faers"),
               compress_dir = tempdir())`

And the error information is:
Error in handle_setopt(handle, ..., noprogress = TRUE) : 
  Invalid or unsupported value when setting curl option 'timeout'
In addition: Warning message:
In handle_setopt(handle, ..., noprogress = TRUE) :
  NAs introduced by coercion to integer range

Would you please suggest how to get this fixed?
Thank you.
Li

**Comment by Yunuuuu** [comment]
It seems the newest `curl` breakdown the package. A quick fix maybe use curl version of 5.0.0

**Comment by Yunuuuu** [comment]
should fix by 2610efcf30515f3cf5e438c2ee8a93b0dec89b4a
